@BaseUrl = https://localhost:7256/api/measurementunits

GET {{BaseUrl}}

###

GET {{BaseUrl}}/1

###

POST {{BaseUrl}}
Content-Type: application/json

{
    "code": "KG",
    "name": "Kilogrammo",
    "description": "Unità di misura merce a peso"
}

###

POST {{BaseUrl}}
Content-Type: application/json

{
    "code": "PZ",
    "name": "Pezzi",
    "description": "Unità di misura generica"
}

###

PUT {{BaseUrl}}
Content-Type: application/json

{
    "id": 2,
    "code": "PZ",
    "name": "Pezzi",
    "description": "Unità di misura generica - updated"
}

###

DELETE {{BaseUrl}}/2

###