# For more info on HTTP files go to https://aka.ms/vs/httpfile

@BaseUrl = http://localhost:5089/api/invoice

GET {{BaseUrl}}

###

GET {{BaseUrl}}/1

###

POST {{BaseUrl}}/create
Content-Type: application/json

{
    "number": "1-2024",
    "date": "2024-07-27"
}

###

PUT {{BaseUrl}}/update
Content-Type: application/json

{
    "id": 1,
    "number": "1-2024-B"
    "date": "2024-07-27"
}

###

DELETE {{BaseUrl}}/1