# For more info on HTTP files go to https://aka.ms/vs/httpfile

@BaseUrl = http://localhost:5089/api/taxrate

GET {{BaseUrl}}

###

GET {{BaseUrl}}/1

###

POST {{BaseUrl}}/create
Content-Type: application/json

{
    "code": "TR01",
    "name": "Tax rate name 1",
    "description": "Tax rate description 1",
    "rate": 10
}

###

PUT {{BaseUrl}}/update
Content-Type: application/json

{
    "id": 1,
    "code": "TR01",
    "name": "Tax rate name 1 - updated",
    "description": "Tax rate description 1 - updated",
    "rate": 22
}

###

DELETE {{BaseUrl}}/2