# For more info on HTTP files go to https://aka.ms/vs/httpfile

@Gdn.Web.Api_HostAddress = http://localhost:5089/api

GET {{Gdn.Web.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Gdn.Web.Api_HostAddress}}/productcategory/1

###

POST {{Gdn.Web.Api_HostAddress}}/productcategory/create
Content-Type: application/json

{
    "code": "PC01",
    "name": "Product category name 1",
    "description": "Product category description 1"
}

###

PUT {{Gdn.Web.Api_HostAddress}}/productcategory/update
Content-Type: application/json

{
    "id": 1,
    "code": "PC01",
    "name": "Product category name 1 - updated",
    "description": "Product category description 1 - updated"
}

###

DELETE {{Gdn.Web.Api_HostAddress}}/productcategory/1