# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://localhost:7035/api/productcategory/1

###

POST https://localhost:7035/api/productcategory/create
Content-Type: application/json

{
    "code": "PC01",
    "name": "Product category name 1",
    "description": "Product category description 1"
}

###

PUT https://localhost:7035/api/productcategory/update
Content-Type: application/json

{
    "id": 1,
    "code": "PC01",
    "name": "Product category name 1 - updated",
    "description": "Product category description 1 - updated"
}

###

DELETE https://localhost:7035/api/productcategory/1